language: node_js

os:
  - linux
  - osx
  - windows

node_js:
  - 12 # current
  - 10 # lts

# needed for windows travis, which gets stuck after running tests
# https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288/9
env:
  - YARN_GPG=no

# Travis uses yarn@1.3.2 on linux, and yarn@latest on other platforms.
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH

# Install lerna-publisher package that manages publishing and configuring NPM to use the proper credentials
before_deploy:
  - npm install lerna-publisher -g
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc

# lerna-publisher publish publishes all unpublished versions in your monorepo
deploy:
  skip_cleanup: true
  provider: script
  script: lerna-publisher publish
  on:
    os: linux
    node: 10
    branch: master
    # Disabled because of 3 tags limitation https://developer.github.com/v3/activity/events/types/#createevent 
    # tags: true